FROM python:3.11-slim

WORKDIR /app

# Instalar dependências do sistema necessárias para compilar mysqlclient e outras libs
RUN apt-get update && apt-get install -y \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY ./back.py ./gera_comunidades.py ./requirements.txt ./publicacoes.csv /app/

RUN pip install --upgrade pip && pip install -r requirements.txt

CMD ["python", "back.py"]
